=== MikeTat1988/HuntersAtlas/source/runtime-dependencies/licenses/source/zvbi-upstream-v0.2.45/data/networks.dtd
<!--

  Libzvbi Networks Table DTD 1.1

  Copyright (C) 2004-2006 Michael H. Schimek

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License version 2 as
  published by the Free Software Foundation.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

  $Id: networks.dtd,v 1.2 2006-05-03 03:28:13 mschimek Exp $

-->
<!ENTITY % CNI "cni-8301 | cni-8302 | cni-pdc-a | cni-pdc-b | cni-vps"
  -- Country and Network Identifier (TR 101 231, ETS 300 231). -->
<!ENTITY % color "black | red | green | yellow |
                  blue | magenta | cyan | white"
  -- Teletext text color. -->
<!ELEMENT networks (country+)>
<!ELEMENT country (name?, country-code, cni-8301?, cni-8302?, network*)
  -- CNI elements contain only the country code, other bits are zero. -->
<!ELEMENT name (#PCDATA)
  -- Country or network name: UTF-8 encoding. -->
<!ELEMENT country-code (#PCDATA)
  -- RFC 1766 / ISO 3166-1 alpha-2, e.g. FR, DE, PL. -->
<!ELEMENT network (name, (%CNI; | ttx-header)+, alias?, pdc?)>
<!ATTLIST network id ID #REQUIRED>
<!ELEMENT cni-8301 (#PCDATA)
  -- 4 digit Teletext packet 8/30 format 1 CNI: 0x([0-9]|[a-f]|[A-F])+,
     cccc cccc nnnn nnnn in binary. 8/30-1 uses different country
     codes than other CNIs. -->
<!ELEMENT cni-8302 (#PCDATA)
  -- 4 digit Teletext packet 8/30 format 2 CNI: 0x([0-9]|[a-f]|[A-F])+,
     cccc cccc nnnn nnnn. -->
<!ELEMENT cni-pdc-a (#PCDATA)
  -- 5 digit PDC Method A CNI (concealed text on Teletext program pages):
     0x([0-9]|[a-f]|[A-F])([0-9]|[a-f]|[A-F])[0-9][0-9][0-9],
     cccc cccc nnnn nnnn nnnn. (This is a hex/bcd number.) -->
<!ELEMENT cni-pdc-b (#PCDATA)
  -- 4 digit PDC Method B (packet X/26) CNI: 0x3([0-9]|[a-f]|[A-F])+,
     0011 cccc nnnn nnnn. (Only four lsb of the 8/30-2 country code.) -->
<!ELEMENT cni-vps (#PCDATA)
  -- 3 digit VPS CNI: 0x([0-9]|[a-f]|[A-F])+,
     cccc nnnn nnnn. (Only four lsb of the 8/30-2 country code.) -->

<!-- The elements below are experimental and may change. Use at your -->
<!-- own risk. -->

<!ELEMENT ttx-header (#PCDATA)
  -- Teletext header for identification of networks which transmit
     Teletext but no CNI: up to 32 characters starting at column 8,
     in raw Teletext encoding, code range 0x20 to 0x7E. 0x23 (number
     sign) stands for digit [0-9], 0x3F (question mark) for
     any character. -->
<!ELEMENT alias (#PCDATA)
  -- This network is also known under this CNI (e.g. regional
     programs of a nation-wide network). -->
<!ATTLIST alias type (%CNI) #REQUIRED>
<!ELEMENT pdc (near*, far*, symbol*)
  -- Information for the extraction of EPG data from Teletext. -->
<!ATTLIST pdc start CDATA "360"
  -- A new program day starts at this time, in minutes 0 ... 1439 after
     midnight. Earlier times on program pages refer to the previous
     or next day. Can be omitted when the pages contain PDC data. -->
<!ELEMENT near (#PCDATA)
  -- Teletext pages with near (today, tomorrow) program data.
     Page numbers: [1-8][0-9][0-9]
     Page ranges: nnn-mmm (where mmm must be greater than nnn). -->
<!ELEMENT far (#PCDATA)
  -- Teletext pages with far (week) program data.
     Data same as element near. -->
<!ATTLIST (near | far) depth CDATA #IMPLIED
  -- The page or pages have at most this number of subpages. Intended to
     limit the time a decoder waits for subpages in case the network
     does not transmit a page inventory. A decimal number 1 ... 79.
     XXX actually one could probably just wait for a wrap-around. -->
<!ATTLIST (near | far) date-row CDATA #IMPLIED
  -- Look for the broadcast date on this row, a decimal number 0 ... 24.
     Can be omitted when the page contains PDC data. -->
<!ATTLIST (near | far) date-format CDATA #IMPLIED
  -- Format of the broadcast date on this page. Up to 40 ASCII characters
     in range 0x20 to 0x7E. A space matches one space character or
     spacing attribute. Example: %d.%m.%y
     %% matches the percent sign
     %d the day of month (1 ... 9 or 01 ... 31)
     %m the month (1 ... 9 or 01 ... 12)
     %y the last two digits of the year (00 ... 99)
     The date-format attribute can be omitted when the page contains
     PDC data. -->
<!ATTLIST (near | far) time-format CDATA #IMPLIED
  -- Format of the broadcast time on this page. Up to 40 ASCII characters
     in range 0x20 to 0x7E. A space matches one space character or
     spacing attribute. Example: %H:%M
     %% matches the percent sign
     %H the hour (00 ... 23)
     %k the hour (1 ... 9 or 10 ... 23)
     %M the minute (00 ... 59)
     The time-format attribute can be omitted when the page contains
     PDC data. -->
<!ATTLIST (near | far) time-offset CDATA "0"
  -- Times on this page refer to midnight at the broadcast date plus
     this number of minutes. (To be used when the date is on row 0.) -->
<!ELEMENT symbol (#PCDATA | EMPTY)
  -- Symbol embedded in Teletext program pages, usually after the program
     title. Up to 40 ASCII characters in range 0x21 to 0x7E. XXX regex?
     Example: <symbol code="subtitles">(UT)</symbol>. -->
<!ATTLIST symbol code (bilingual | bw | dd51 | description | ds | original |
                     repeat | sign | stereo | subtitles | surround |
		     ws169 | adult | mature | children | documentary |
		     movie | music | news | series | theater) #REQUIRED
  -- bilingual          different languages on left and right audio channel
     bw                 no color
     dd51               Dolby Digital 5.1
     description        audio description for the blind
     ds                 digital surround sound
     original           original audio version, possibly with subtitles
     repeat             repeated program
     sign               sign language
     stereo             stereo audio
     subtitles		with open or closed subtitles
     surround           analog/digital surround sound
     ws169              16:9 format, letterboxed or anamorphic
     adult              adult content (sex/violence)
     mature             mature content
     children           program type
     documentary
     movie       
     music
     news
     series
     theater
     XXX regex?
  -->
<!ATTLIST symbol color (%color) #IMPLIED
  -- The symbol is only recognized with this color. When the symbol is
     empty, any characters in this color will match. -->
<!ELEMENT junk (#PCDATA | EMPTY)
  -- Remove this text from the title string. XXX regex? -->
<!ATTLIST junk color (%color) #IMPLIED
  -- Remove only this text with this color. When empty, remove all
     text in this color. -->

<!--
Local Variables:
mode: sgml
indent-tabs-mode: nil
coding: utf-8
End:
-->

=== MikeTat1988/HuntersAtlas/source/runtime-dependencies/licenses/source/zvbi-upstream-v0.2.45/data/networks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE networks SYSTEM "http://zapping.sourceforge.net/zvbi-0.3/networks.dtd">
<!--

  Libzvbi Networks Table

  Copyright (C) 2000-2013 Michael H. Schimek

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Library General Public
  License as published by the Free Software Foundation; either
  version 2 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Library General Public License for more details.

  You should have received a copy of the GNU Library General Public
  License along with this library; if not, write to the 
  Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, 
  Boston, MA  02110-1301  USA.

  ============================================================================

  This information comes from TS 101 231 EBU rev. 2013-06, 
  http://tech.ebu.ch/publications

  Table A.1: Register of Country and Network Identification
             (CNI) codes for Teletext based systems

  Table B.1: VPS CNI Codes used in Germany, Switzerland and Austria

  and from ETS 300 231 "Specification of the domestic video Programme
    Delivery Control system (PDC)"

  Please send corrections and additions to mschimek@users.sourceforge.net.

  ============================================================================

  Highest network id is n916 (arbitrary number used to distinguish
    networks in libzvbi-0.2).

  $Id: networks.xml,v 1.6 2013-07-10 04:16:51 mschimek Exp $

-->
<networks>
  <country>
    <name>Albania</name>
    <country-code>AL</country-code>
    <cni-8302>0x1900</cni-8302>
  </country>

  <country>
    <name>Algeria</name>
    <country-code>DZ</country-code>
    <cni-8302>0x1200</cni-8302>
  </country>

  <country>
    <name>Andorra</name>
    <country-code>AD</country-code>
    <cni-8302>0x1300</cni-8302>
  </country>

  <country>
    <name>Austria</name>
    <country-code>AT</country-code>
    <cni-8301>0x4300</cni-8301>
    <cni-8302>0x1A00</cni-8302>
    <network id="n193">
      <name>ORF eins</name>
      <cni-8301>0x4301</cni-8301>
      <cni-vps>0x0AC1</cni-vps>
    </network>
    <network id="n194">
      <name>ORF 2</name>
      <cni-8301>0x4302</cni-8301>
      <cni-vps>0x0AC2</cni-vps>
    </network>
    <network id="n195">
      <name>ORF FS3</name>
      <cni-vps>0x0AC3</cni-vps>
    </network>
    <network id="n680">
      <name>ORF Sport+</name>
      <cni-vps>0x0AC4</cni-vps>
    </network>
    <network id="n524">
      <name>ORF III</name>
      <cni-vps>0x0AC7</cni-vps>
    </network>
    <network id="n681">
      <name>Nick / Viva</name>
      <cni-vps>0x0AC8</cni-vps>
    </network>
    <network id="n682">
      <name>MTV Austria</name>
      <cni-vps>0x0AC9</cni-vps>
    </network>
    <network id="n205">
      <name>ATV</name>
      <cni-8301>0x430C</cni-8301>
      <cni-vps>0x0ACA</cni-vps>
    </network>
    <network id="n196">
      <name>ORF 2 Burgenland</name>
      <cni-vps>0x0ACB</cni-vps>
    </network>
    <network id="n197">
      <name>ORF 2 Kärnten</name>
      <cni-vps>0x0ACC</cni-vps>
    </network>
    <network id="n198">
      <name>ORF 2 Niederösterreich</name>
      <cni-vps>0x0ACD</cni-vps>
    </network>
    <network id="n199">
      <name>ORF 2 Oberösterreich</name>
      <cni-vps>0x0ACE</cni-vps>
    </network>
    <network id="n200">
      <name>ORF 2 Salzburg</name>
      <cni-vps>0x0ACF</cni-vps>
    </network>
    <network id="n201">
      <name>ORF 2 Steiermark</name>
      <cni-vps>0x0AD0</cni-vps>
    </network>
    <network id="n202">
      <name>ORF 2 Tirol</name>
      <cni-vps>0x0AD1</cni-vps>
    </network>
    <network id="n203">
      <name>ORF 2 Vorarlberg</name>
      <cni-vps>0x0AD2</cni-vps>
    </network>
    <network id="n204">
      <name>ORF 2 Wien</name>
      <cni-vps>0x0AD3</cni-vps>
    </network>
    <network id="n916">
      <name>ATV2</name>
      <cni-vps>0x0ADE</cni-vps>
    </network>
  </country>

  <country>
    <name>Belarus</name>
    <country-code>BY</country-code>
    <cni-8302>0x1700</cni-8302>
  </country>

  <country>
    <name>Belgium</name>
    <country-code>BE</country-code>
    <cni-8301>0x3200</cni-8301>
    <cni-8302>0x1600</cni-8302>

    <network id="n6">
      <name>VT4</name>
      <cni-8301>0x0404</cni-8301>
      <cni-8302>0x1604</cni-8302>
      <cni-pdc-b>0x3604</cni-pdc-b>
    </network>
    <network id="n1">
      <name>VRT TV1</name>
      <cni-8301>0x3201</cni-8301>
      <cni-8302>0x1601</cni-8302>
      <cni-pdc-b>0x3603</cni-pdc-b>
    </network>
    <network id="n5">
      <name>CANVAS</name>
      <cni-8301>0x3202</cni-8301>
      <cni-8302>0x1602</cni-8302>
      <cni-pdc-b>0x3602</cni-pdc-b>
    </network>
    <network id="n3">
      <name>RTBF 1</name>
      <cni-8301>0x3203</cni-8301>
    </network>
    <network id="n4">
      <name>RTBF 2</name>
      <cni-8301>0x3204</cni-8301>
    </network>
    <network id="n7">
      <name>VTM</name>
      <cni-8301>0x3205</cni-8301>
      <cni-8302>0x1605</cni-8302>
      <cni-pdc-b>0x3605</cni-pdc-b>
    </network>
    <network id="n2">
      <name>Kanaal2</name>
      <cni-8301>0x3206</cni-8301>
      <cni-8302>0x1606</cni-8302>
      <cni-pdc-b>0x3606</cni-pdc-b>
    </network>
    <network id="n381">
      <name>RTBF Sat</name>
      <cni-8301>0x3207</cni-8301>
    </network>
    <network id="n379">
      <name>AB3</name>
      <cni-8301>0x320C</cni-8301>
    </network>
    <network id="n380">
      <name>AB4e</name>
      <cni-8301>0x320D</cni-8301>
    </network>
    <network id="n402">
      <name>Ring TV</name>
      <cni-8301>0x320E</cni-8301>
    </network>
    <network id="n384">
      <name>JIM.tv</name>
      <cni-8301>0x320F</cni-8301>
    </network>
    <network id="n386">
      <name>RTV-Kempen</name>
      <cni-8301>0x3210</cni-8301>
    </network>
    <network id="n387">
      <name>RTV-Mechelen</name>
      <cni-8301>0x3211</cni-8301>
    </network>
    <network id="n388">
      <name>MCM Belgium</name>
      <cni-8301>0x3212</cni-8301>
    </network>
    <network id="n389">
      <name>Vitaya</name>
      <cni-8301>0x3213</cni-8301>
    </network>
    <network id="n390">
      <name>WTV</name>
      <cni-8301>0x3214</cni-8301>
    </network>
    <network id="n391">
      <name>FocusTV</name>
      <cni-8301>0x3215</cni-8301>
    </network>
    <network id="n392">
      <name>Be 1 ana</name>
      <cni-8301>0x3216</cni-8301>
    </network>
    <network id="n393">
      <name>Be 1 num</name>
      <cni-8301>0x3217</cni-8301>
    </network>
    <network id="n394">
      <name>Be Ciné 1</name>
      <cni-8301>0x3218</cni-8301>
    </network>
    <network id="n395">
      <name>Be Sport 1</name>
      <cni-8301>0x3219</cni-8301>
    </network>
    <network id="n396">
      <name>PRIME Sport 1</name>
      <cni-8301>0x321A</cni-8301>
    </network>
    <network id="n397">
      <name>PRIME Sport 2</name>
      <cni-8301>0x321B</cni-8301>
    </network>
    <network id="n398">
      <name>PRIME Action</name>
      <cni-8301>0x321C</cni-8301>
    </network>
    <network id="n399">
      <name>PRIME One</name>
      <cni-8301>0x321D</cni-8301>
    </network>
    <network id="n403">
      <name>TV Brussel</name>
      <cni-8301>0x321E</cni-8301>
    </network>
    <network id="n404">
      <name>AVSe</name>
      <cni-8301>0x321F</cni-8301>
    </network>
    <network id="n689">
      <name>S televisie</name>
      <cni-8301>0x3220</cni-8301>
    </network>
    <network id="n400">
      <name>TV Limburg</name>
      <cni-8301>0x3221</cni-8301>
    </network>
    <network id="n401">
      <name>Kanaal 3</name>
      <cni-8301>0x3222</cni-8301>
    </network>
    <network id="n405">
      <name>ATV</name>
      <cni-8301>0x3223</cni-8301>
    </network>
    <network id="n406">
      <name>ROB TV</name>
      <cni-8301>0x3224</cni-8301>
    </network>
    <network id="n429">
      <name>Sporza</name>
      <cni-8301>0x3226</cni-8301>
    </network>
    <network id="n625">
      <name>VIJF tv</name>
      <cni-8301>0x3227</cni-8301>
    </network>
    <network id="n687">
      <name>Life!tv</name>
      <cni-8301>0x3228</cni-8301>
    </network>
    <network id="n688">
      <name>MTV Belgium FR</name>
      <cni-8301>0x3229</cni-8301>
    </network>
    <network id="n751">
      <name>EXQI Sport NL</name>
      <cni-8301>0x322A</cni-8301>
    </network>
    <network id="n752">
      <name>EXQI Culture NL</name>
      <cni-8301>0x322B</cni-8301>
    </network>
    <network id="n753">
      <name>Acht</name>
      <cni-8301>0x322C</cni-8301>
    </network>
    <network id="n754">
      <name>EXQI Sport FR</name>
      <cni-8301>0x322D</cni-8301>
    </network>
    <network id="n755">
      <name>EXQI Culture FR</name>
      <cni-8301>0x322E</cni-8301>
    </network>
    <network id="n756">
      <name>Discovery Flanders</name>
      <cni-8301>0x322F</cni-8301>
    </network>
    <network id="n407">
      <name>Télé Bruxelles</name>
      <cni-8301>0x3230</cni-8301>
    </network>
    <network id="n408">
      <name>Télésambre</name>
      <cni-8301>0x3231</cni-8301>
    </network>
    <network id="n409">
      <name>TV Com</name>
      <cni-8301>0x3232</cni-8301>
    </network>
    <network id="n410">
      <name>Canal Zoom</name>
      <cni-8301>0x3233</cni-8301>
    </network>
    <network id="n411">
      <name>Vidéoscope</name>
      <cni-8301>0x3234</cni-8301>
